spring:
  application:
    name: feign-demo

server:  port: 8081
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: localhost:8761/eureka/
    region: defaultZone