spring:
  applicaiton:
    name: eureka-server

server:
  port: ${PORT:8761}
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    appname: ${spring.applicaiton.name}
  client:
    register-with-eureka: ${BOOL_REGISTER:true}
    fetch-registry: ${BOOL_FETCH:true}
    service-url:
      defaultZone: ${EUREKA_SERSER:http://${eureka.instance.hostname}:${server.port}/eureka/}
    region: defaultZone
